"""make_report.py -- merge per-host CSV runs -> markdown benchmark report.

Collects every reports/bench/<host>/*.csv across machines (push them back via git)
and writes reports/benchmark_report.md. With --compare A B it also emits a
head-to-head delta table (latency delta, speedup, memory delta) -- used to show the
effect of a manual optimization (variant A baseline vs variant B manual result).

    uv run python scripts/make_report.py
    uv run python scripts/make_report.py --compare D_cpu D_manual
"""
from __future__ import annotations

import argparse, csv, glob, os, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import REPORTS_DIR, banner  # noqa: E402

from tabulate import tabulate

FIELDNAMES = ["host", "variant", "dtype", "opt_level", "act_provider",
              "threads", "p50", "p95", "p99", "enc_p50", "dec_p50", "model_rss_mb"]


def load_all():
    rows = []
    for p in sorted(Path(REPORTS_DIR / "bench").rglob("*.csv")):
        with p.open() as f:
            for r in csv.DictReader(f):
                rows.append({k: r.get(k, "") for k in FIELDNAMES} | {"_file": p.name})
    return rows


def num(x):
    try:
        return float(x)
    except Exception:
        return float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--compare", nargs=2, metavar=("A", "B"), default=None)
    args = ap.parse_args()
    rows = load_all()
    banner(f"make_report: {len(rows)} rows across hosts")
    md = ["# Benchmark report\n", f"Total runs: {len(rows)}\n",
          "## All measurements\n",
          tabulate([[r.get(k, "") for k in FIELDNAMES] for r in rows],
                   headers=FIELDNAMES, tablefmt="pipe")]
    if args.compare:
        a, b = args.compare
        ar = [r for r in rows if r["variant"] == a]
        br = [r for r in rows if r["variant"] == b]
        delta_rows = []
        for ra in ar:
            # match on host + opt_level + provider threads
            cand = [rb for rb in br if rb["host"] == ra["host"] and rb["opt_level"] == ra["opt_level"]
                    and rb["act_provider"] == ra["act_provider"] and rb["threads"] == ra["threads"]]
            if not cand:
                continue
            rb = cand[0]
            sp = num(rb["p50"]) / num(ra["p50"]) if num(ra["p50"]) else float("nan")
            delta_rows.append([ra["host"], ra["opt_level"], ra["act_provider"],
                               f"{num(ra['p50']):.1f}", f"{num(rb['p50']):.1f}",
                               f"{num(rb['p50'])-num(ra['p50']):+.1f}",
                               f"{sp:.2f}x",
                               f"{num(rb['model_rss_mb'])-num(ra['model_rss_mb']):+.0f}"])
        md += ["\n## Head-to-head: %s vs %s\n" % (a, b),
               tabulate(delta_rows,
                        headers=["host", "opt_level", "provider", f"{a} p50(ms)",
                                 f"{b} p50(ms)", "Δ ms", f"{b}/{a} speedup", "Δ rss(MB)"],
                        tablefmt="pipe")]
    md += ["\n> Generated by scripts/make_report.py from reports/bench/**/*.csv\n"]
    out = REPORTS_DIR / "benchmark_report.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(md) if isinstance(md, list) else md)
    print(out)


if __name__ == "__main__":
    main()